<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ArbitrageBot-27000f1a-385c-40d3-a581-8bb13b8b1d32</UserSecretsId>
    <RootNamespace>ArbitrageBot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CryptoClients.Net" Version="5.6.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
